version: '3'

tasks:
  test-local:
    cmds:
      - cd ../discord-app && npm run migrate
      - docker compose exec -e APP_ENV=unittest backend go test {{.CLI_ARGS | default "./..."}}

  test-ci:
    cmds:
      - APP_ENV=unittest go test ./...

  lint:
    cmds:
      - golangci-lint run
      - gocyclo .
      - gocognit .
