name: Backend Test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**/*.go'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER_UNITTEST: ${{ secrets.POSTGRES_USER_UNITTEST }}
      POSTGRES_PASSWORD_UNITTEST: ${{ secrets.POSTGRES_PASSWORD_UNITTEST }}
      POSTGRES_DB_UNITTEST: ${{ secrets.POSTGRES_DB_UNITTEST }}

    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose up -d --build backend unittest-db && 
          docker compose exec backend task test-ci &&
          docker compose down
